ainaproj/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from blog.views import search_posts
from main.views import search_events

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)), # for the debug toolbar

    # the ground-0 urlconf
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),

    # silent search activity
    path('search_events/', search_events, name='event_ajax-search'),
    path('search_posts/', search_posts, name='post_ajax-search')
]

blog/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static



app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('<str:url_aware_title>/', PostDetailView.as_view(), name='post-detail'),

    # we may not necessarily need to implement a blog create page,
    # because then we have to validate using a LoginRequiredMixin on the view.
    # the admin can handle this, but we may still use it to make less people have access to the admin
    # though we may create certain permissions for their User instances.
    # path('create/', PostCreateView.as_view(), name='post-create'),
    # adding a path for the updateview
    # path('update/<int:id>/', PostUpdateView.as_view(), name='post-update'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'
urlpatterns = [
    path('about/', AboutView.as_view(), name='about_view'),
    path('causes/', CausesView.as_view(), name='causes_view'),
    path('contact/', ContactView.as_view(), name='contact_view'),
    path('donate/', DonateView.as_view(), name='donate_view'),
    path('event-single/<int:id>/', Event_Single_View.as_view(), name='event-single_view'),
    path('events/', EventView.as_view(), name='events_view'),
    path('event-single-gallery/<int:id>/', Event_Single_Gallery.as_view(), name='event-single-gallery_view'),
    path('events-gallery/', GalleryView.as_view(), name='events-gallery_view'),

    # making the indexview the ground-0 view of the site
    path('', IndexView.as_view(), name='home_view'),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
		<title>{% block title %}  {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/logo.png'  %}">
    <link href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Overpass:300,400,400i,600,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">

    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block styles %}
		
		{% endblock %}

  </head>
  <body>
		{% include 'nav.html' %}

		{% block overlay %}  
			<div 
				class="hero-wrap" 
				style="background-image: url('{% block overlay_img_url %}  {% endblock %}');" 
				data-stellar-background-ratio="0.5">

				<div class="overlay"></div>
				<div class="container">
					<div class="row no-gutters slider-text align-items-center justify-content-center" data-scrollax-parent="true">
						<div class="col-md-7 ftco-animate text-center" data-scrollax=" properties: { translateY: '70%' }">
							<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">
								<span class="mr-2">
									<a href="/home">Home</a>
								</span> 
								<span class="mr-2">
									<a href="blog.html">
										<span>{% block other_link %} {% endblock %}</span>
									</a>
								</span> 
							</p>
							<h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">{% block overlay_name %} {% endblock %}</h1>
						</div>
					</div>
				</div>
			</div>
		{% endblock %}

		{% include 'messages.html' %}

		{% block content %}
		{% endblock %}

		{% include 'footer.html' %}
		

		<!-- loader -->
		<div id="ftco-loader" class="show fullscreen">
			<svg class="circular" width="48px" height="48px">
				<circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
				<circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/>
			</svg>
		</div>
	  
	  <script>
			// suppose the `id` attribute of element is `message_container`.
			var disappearing_message_box = document.getElementById("message_container");
			setTimeout(()=> { 
			  disappearing_message_box.style.display = "none"; 
			  disappearing_message_box.style.height = "0px";
			  disappearing_message_box.classlist.add('not-visible hidden');
			}, 3000);
	  </script>
	  
	  <script 
	  	src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
	  	integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" 
	  	crossorigin="anonymous">
	  </script>
	  <script 
	  	src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" 
	  	integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" 
	  	crossorigin="anonymous">
	  </script>
	  <script 
	  	src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" 
	  	integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" 
	  	crossorigin="anonymous">
	  </script>
	  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
	  <script src="{% static 'js/jquery.min.js' %}"></script>
	  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
	  <script src="{% static 'js/popper.min.js' %}"></script>
	  <script src="{% static 'js/bootstrap.min.js' %}"></script>
	  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
	  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
	  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	  <script src="{% static 'js/aos.js' %}"></script>
	  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
	  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
	  <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
	  <script src="{% static 'js/scrollax.min.js' %}"></script>

	  <script src="{% static 'js/google-map.js' %}"></script>
	  <script src="{% static 'js/main.js' %}"></script>

	  {% block scripts %} 
	  
	  {% endblock %}
  </body>
</html>

templates/footer.html
{% load static %}
<footer class="ftco-footer ftco-section img">
	<div class="overlay"></div>
	<div class="container">
		<div class="row mb-5">
			<div class="col-md-3">
				<div class="ftco-footer-widget mb-4 center">
					<h2 class="ftco-heading-2">About Us</h2>
					<p>Abosede Aina Charity Foundation's main purpose is to make a positive impact on society by addressing issues such as poverty, education, especially health care, and the environment. </p>
					<ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
						<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
						<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
						<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
					</ul>
				</div>
			</div>
			<div class="col-md-4">
				<div class="ftco-footer-widget mb-4">
					<h2 class="ftco-heading-2 center">Recent Events</h2>
					{% for event in footer_events %}
						<div class="block-21 mb-4 d-flex">
							<a class="blog-img mr-4" href="{{event.get_absolute_url}}" style="background-image: url('{{event.image.url}}');"></a>
							<div class="text">
							<h3 class="heading"><a href="{{event.get_absolute_url}}">{{event.name}}</a></h3>
							<div class="meta">
								<div><a href="{{event.get_absolute_url}}"><span class="icon-calendar"></span> {{event.date}}</a></div>
								<div><a href="{{event.get_absolute_url}}"><span class="icon-person"></span> {{event.creator}}</a></div>
								<div><a href="{{event.get_absolute_url}}"><span class="icon-chat"></span> {{event.comment_count}}</a></div>
							</div>
							</div>
						</div>
					{% endfor %}
					
				</div>
			</div>
			<div class="col-md-2">
				 <div class="ftco-footer-widget mb-4 ml-md-4 center">
					<h2 class="ftco-heading-2">Site Links</h2>
					<ul class="list-unstyled">
						<li><a href="{% url 'main:home_view' %}" class="py-2 d-block">Home</a></li>
						<li><a href="{% url 'main:about_view' %}" class="py-2 d-block">About</a></li>
						<li><a href="{% url 'main:donate_view' %}" class="py-2 d-block">Donate</a></li>
						<li><a href="{% url 'main:events_view' %}" class="py-2 d-block">Event</a></li>
						<li><a href="{% url 'main:events-gallery_view' %}" class="py-2 d-block">Gallery</a></li>
						<li><a href="{% url 'main:contact_view' %}" class="py-2 d-block">Contact</a></li>
					</ul>
				</div>
			</div>
			<div class="col-md-3">
				<div class="ftco-footer-widget mb-4">
					<h2 class="ftco-heading-2 center">Have any Questions?</h2>
					<div class="block-23 mb-3">
						<ul>
							<li>
								<a href="https://www.google.com/maps/search/+Plot+53+Block+99+Flat+1,+Iba+Housing+Estate,+Iba-Ojo,+Lagos/@6.4918381,3.195785,17z/data=!3m1!4b1">
									<span class="icon icon-map-marker"></span>
									<span class="text">Plot 53 Block 99 Flat 1, Iba Housing Estate, Iba-Ojo, Lagos</span>
								</a>
							</li>
							<li>
								<a href="tel:+2348168819022">
									<span class="icon icon-phone"></span><span class="text">+2348168819022</span>
								</a>
							</li>
							<li>
								<a href="mailto:abosedeainafoundation@aol.com">
									<span class="icon icon-envelope"></span>
									<span class="text">abosedeainafoundation@aol.com</span>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 text-center">
				<p>Copyright &copy;<script>document.write(new Date().getFullYear());</script> Niyexdroid Technologies </p>
			</div>
		</div>
	</div>
</footer>

templates/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <div class="{{ message.tags }} sticky-top w-100" id="message_container">
                <h2 class=" text-center">{{ message }}</h2>
            </div>
        {% endfor %}
    </ul>   
{% endif %}

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	<div class="container">
	  <a class="navbar-brand" href="{% url 'main:home_view'%}">
			<img src="{% static 'images/logo.png' %}" max-width="40" height="40" alt="logo">
	  </a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="oi oi-menu"></span> 
	  </button>

	  <div class="collapse navbar-collapse" id="ftco-nav">
			<ul class="navbar-nav ml-auto">
			  <li class="nav-item"><a href="{% url 'main:home_view'%}" class="nav-link">Home</a></li>
			  <li class="nav-item"><a href="{% url 'main:about_view'%}" class="nav-link">About</a></li>
			  <li class="nav-item"><a href="{% url 'main:donate_view'%}" class="nav-link">Donate</a></li>
			  <li class="nav-item"><a href="{% url 'main:events_view'%}" class="nav-link">Event</a></li>
			  <li class="nav-item"><a href="{% url 'blog:post-list'%}" class="nav-link">Blogpost</a></li>
			  <li class="nav-item"><a href="{% url 'main:events-gallery_view'%}" class="nav-link">Gallery</a></li>
			  <li class="nav-item"><a href="{% url 'main:contact_view'%}" class="nav-link">Contact</a></li>
			</ul>
	  </div>
	</div>
</nav>

templates/volunteer_form.html
{% load static %}

<section class="ftco-section-3 img" id="volunteer" style="background-image: url({% static 'images/bg_3.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row d-md-flex">
          <div class="col-md-6 d-flex ftco-animate">
              <div class="img img-2 align-self-stretch" style="background-image: url({% static 'images/bg_4.jpg' %});"></div>
          </div>
          <div class="col-md-6 volunteer pl-md-5 ftco-animate">
              <h3 class="mb-3">Be a volunteer</h3>
              <form action="#" class="volunter-form" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <input type="text" name="volunteer_name" class="form-control" placeholder="Your Name">
                </div>
                <div class="form-group">
                  <input type="text" name="volunteer_email" class="form-control" placeholder="Your Email">
                </div>
                <div class="form-group">
                  <textarea name="volunteer_message" cols="30" rows="3" class="form-control" placeholder="Message"></textarea>
                </div>
                <div class="form-group">
                  <input type="submit" name="send_email_messages" value="Send Message" class="btn btn-white py-3 px-5">
                </div>
              </form>
          </div>    			
        </div>
    </div>
</section>